%YAML:1.0

# Topic name in rosbag
PointCloudTopic: "/livox/lidar"
ImageTopic: "/camera/color/image_raw"

ExtrinsicMat: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  # +90 ^-> (Camera is base frame now) AND THAT'S TRUE:
  # (https://github.com/hku-mars/livox_camera_calib/issues/40#issuecomment-1067578854)
  data: [ -0.00068, 0.99995, 0.00977, 0.05740,
          0.07716, -0.00969, 0.99697, 0.16166,
          0.99702, 0.00143, -0.07715, -0.00210,
          0, 0, 0, 1 ]
# Params for Canny Edge Extraction
Canny.gray_threshold: 10
Canny.len_threshold: 200 # 100

# Params for Voxel Cutting & Plane Fitting & Edge Extraction
Voxel.size: 2.0 # 2.0
Voxel.down_sample_size: 0.02 # 0.04
Plane.min_points_size: 30
Plane.normal_theta_min: 45
Plane.normal_theta_max: 135
Plane.max_size: 8
Ransac.dis_threshold: 0.02
Edge.min_dis_threshold: 0.03 # 0.06
Edge.max_dis_threshold: 0.06 # 0.1
